---
- hosts: server
  sudo: yes
  roles:
  - role: znzj.rbenv
    rbenv_ruby_version: 2.1.3
  - role: docker.ubuntu
  post_tasks:
    - name: add local insecure registry
      lineinfile: dest=/etc/default/docker
                  line="DOCKER_OPTS='--insecure-registry 192.168.200.100:5000'"
    - name: restart docker
      service: name=docker state=restarted

- hosts: server
  tasks:
  - name: configure locale
    shell: locale-gen ru_RU.UTF-8
    sudo: yes
  - name: apt-get update
    sudo: yes
    apt: update_cache=yes
#   - name: "fix bug in ansible/upstart: https://github.com/ansible/ansible-modules-core/issues/1170"
#     sudo: yes
#     file: path=/etc/init.d/docker.io state=absent
  - name: install docker-py
    sudo: yes
    pip: name=docker-py version=1.1.0
  - name: add user vagrant to docker group
    sudo: yes
    user: name=vagrant groups=vagrant,sudo,docker
#  - name: change options for docker daemon
#    sudo: yes
#    lineinfile: dest=/etc/default/docker.io line='DOCKER_OPTS="--tlsverify=false"'
  - name: restart docker
    sudo: yes
    service: name=docker state=restarted
  - name: create /etc/haproxy
    sudo: yes
    file: path=/etc/haproxy state=directory
  - name: copy balancer config
    sudo: yes
    copy: src=../../etc/haproxy/haproxy.cfg dest=/etc/haproxy/haproxy.cfg
  - name: install balancer
    docker:
      docker_api_version: "1.18"
      name: balancer
      image: "{{ docker_registry }}/example/balancer:latest"
      state: restarted
      ports:
      - "80:80"
      volumes:
      - /etc/haproxy/:/etc/haproxy/
